#!/bin/sh
picom &
feh --bg-scale ~/.config/bspwm/maybe.jpg &
$HOME/.config/polybar/start.sh &
setxkbmap -layout us,ru -variant -option grp:alt_shift_toggle,terminate:ctrl_alt_bksp &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config focus_follows_pointer false

bspc config focused_border_color "#89bfcf"
bspc config normal_border_color "#2E3134"
bspc config presel_feedback_color "#4B4F51"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a steam state=floating
